alertmanager:
  enabled: false

kubeStateMetrics:
  enabled: true

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false

grafana:
  grafana.ini:
    auth.anonymous:
      enabled: true
      org_role: Viewer
    http:
      enable_cors: true
      allow_from_origin: "*"
    server:
      root_url: /grafana
      serve_from_sub_path: true
