MASTER_NODES: 192.168.40.131

cni_conf:
  CNI_CONFIG_PRIORITY: "99"

ovn-central:
  requests:
    cpu: "10m"
    memory: "64Mi"
ovs-ovn:
  requests:
    cpu: "10m"
    memory: "64Mi"
kube-ovn-controller:
  requests:
    cpu: "10m"
    memory: "64Mi"
kube-ovn-cni:
  requests:
    cpu: "10m"
    memory: "64Mi"
kube-ovn-pinger:
  requests:
    cpu: "10m"
    memory: "64Mi"
kube-ovn-monitor:
    cpu: "10m"
    memory: "64Mi"
