# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: cdi-override-values
#   namespace: vink
# data:
#   values.yaml: |

---

apiVersion: batch/v1
kind: Job
metadata:
  namespace: vink
  name: cdi-installer
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-3"
spec:
  template:
    metadata:
      name: vink
    spec:
      serviceAccountName: vink
      restartPolicy: OnFailure
      containers:
        - name: cdi-installer
          image: hejianmin/shell:0.0.1-f1a26a48
          env:
            - name: HTTP_PROXY
              value: http://192.168.18.240:7897
            - name: HTTPS_PROXY
              value: http://192.168.18.240:7897
            - name: NO_PROXY
              value: localhost,127.0.0.1,10.233.0.1
          command:
            - /bin/bash
            - -c
            - |``
              set -e

              echo "Installing CDI"
              helm upgrade --install --create-namespace --namespace cdi cdi \
                  oci://registry-1.docker.io/hejianmin/cdi --version 0.0.1 \
                  --wait \
                  --timeout 600s \
                  --debug
      #     volumeMounts:
      #       - name: config-volume
      #         mountPath: /config
      #         readOnly: true
      # volumes:
      #   - name: config-volume
      #     configMap:
      #       name: cdi-override-values
