// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package v1alpha1

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for NodeNetworkInterface
func (this *NodeNetworkInterface) MarshalJSON() ([]byte, error) {
	str, err := NetworkMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for NodeNetworkInterface
func (this *NodeNetworkInterface) UnmarshalJSON(b []byte) error {
	return NetworkUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for NodeNetworkInterface_Node
func (this *NodeNetworkInterface_Node) MarshalJSON() ([]byte, error) {
	str, err := NetworkMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for NodeNetworkInterface_Node
func (this *NodeNetworkInterface_Node) UnmarshalJSON(b []byte) error {
	return NetworkUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for NodeNetworkInterface_NetworkInterface
func (this *NodeNetworkInterface_NetworkInterface) MarshalJSON() ([]byte, error) {
	str, err := NetworkMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for NodeNetworkInterface_NetworkInterface
func (this *NodeNetworkInterface_NetworkInterface) UnmarshalJSON(b []byte) error {
	return NetworkUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for MultusConfig
func (this *MultusConfig) MarshalJSON() ([]byte, error) {
	str, err := NetworkMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for MultusConfig
func (this *MultusConfig) UnmarshalJSON(b []byte) error {
	return NetworkUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for ListNodesNetworkInterfacesRequest
func (this *ListNodesNetworkInterfacesRequest) MarshalJSON() ([]byte, error) {
	str, err := NetworkMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for ListNodesNetworkInterfacesRequest
func (this *ListNodesNetworkInterfacesRequest) UnmarshalJSON(b []byte) error {
	return NetworkUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for ListNodesNetworkInterfacesResponse
func (this *ListNodesNetworkInterfacesResponse) MarshalJSON() ([]byte, error) {
	str, err := NetworkMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for ListNodesNetworkInterfacesResponse
func (this *ListNodesNetworkInterfacesResponse) UnmarshalJSON(b []byte) error {
	return NetworkUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for CreateMultusConfigRequest
func (this *CreateMultusConfigRequest) MarshalJSON() ([]byte, error) {
	str, err := NetworkMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for CreateMultusConfigRequest
func (this *CreateMultusConfigRequest) UnmarshalJSON(b []byte) error {
	return NetworkUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for UpdateMultusConfigRequest
func (this *UpdateMultusConfigRequest) MarshalJSON() ([]byte, error) {
	str, err := NetworkMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for UpdateMultusConfigRequest
func (this *UpdateMultusConfigRequest) UnmarshalJSON(b []byte) error {
	return NetworkUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for Subnet
func (this *Subnet) MarshalJSON() ([]byte, error) {
	str, err := NetworkMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Subnet
func (this *Subnet) UnmarshalJSON(b []byte) error {
	return NetworkUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for IPPool
func (this *IPPool) MarshalJSON() ([]byte, error) {
	str, err := NetworkMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for IPPool
func (this *IPPool) UnmarshalJSON(b []byte) error {
	return NetworkUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for SubnetConfig
func (this *SubnetConfig) MarshalJSON() ([]byte, error) {
	str, err := NetworkMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for SubnetConfig
func (this *SubnetConfig) UnmarshalJSON(b []byte) error {
	return NetworkUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for SubnetConfig_Route
func (this *SubnetConfig_Route) MarshalJSON() ([]byte, error) {
	str, err := NetworkMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for SubnetConfig_Route
func (this *SubnetConfig_Route) UnmarshalJSON(b []byte) error {
	return NetworkUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for IPPoolConfig
func (this *IPPoolConfig) MarshalJSON() ([]byte, error) {
	str, err := NetworkMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for IPPoolConfig
func (this *IPPoolConfig) UnmarshalJSON(b []byte) error {
	return NetworkUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for IPPoolConfig_Route
func (this *IPPoolConfig_Route) MarshalJSON() ([]byte, error) {
	str, err := NetworkMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for IPPoolConfig_Route
func (this *IPPoolConfig_Route) UnmarshalJSON(b []byte) error {
	return NetworkUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for CreateSubnetRequest
func (this *CreateSubnetRequest) MarshalJSON() ([]byte, error) {
	str, err := NetworkMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for CreateSubnetRequest
func (this *CreateSubnetRequest) UnmarshalJSON(b []byte) error {
	return NetworkUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for UpdateSubnetRequest
func (this *UpdateSubnetRequest) MarshalJSON() ([]byte, error) {
	str, err := NetworkMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for UpdateSubnetRequest
func (this *UpdateSubnetRequest) UnmarshalJSON(b []byte) error {
	return NetworkUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for CreateIPPoolRequest
func (this *CreateIPPoolRequest) MarshalJSON() ([]byte, error) {
	str, err := NetworkMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for CreateIPPoolRequest
func (this *CreateIPPoolRequest) UnmarshalJSON(b []byte) error {
	return NetworkUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for UpdateIPPoolRequest
func (this *UpdateIPPoolRequest) MarshalJSON() ([]byte, error) {
	str, err := NetworkMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for UpdateIPPoolRequest
func (this *UpdateIPPoolRequest) UnmarshalJSON(b []byte) error {
	return NetworkUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for DeleteMultusConfigRequest
func (this *DeleteMultusConfigRequest) MarshalJSON() ([]byte, error) {
	str, err := NetworkMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for DeleteMultusConfigRequest
func (this *DeleteMultusConfigRequest) UnmarshalJSON(b []byte) error {
	return NetworkUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for DeleteMultusConfigResponse
func (this *DeleteMultusConfigResponse) MarshalJSON() ([]byte, error) {
	str, err := NetworkMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for DeleteMultusConfigResponse
func (this *DeleteMultusConfigResponse) UnmarshalJSON(b []byte) error {
	return NetworkUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for DeleteSubnetRequest
func (this *DeleteSubnetRequest) MarshalJSON() ([]byte, error) {
	str, err := NetworkMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for DeleteSubnetRequest
func (this *DeleteSubnetRequest) UnmarshalJSON(b []byte) error {
	return NetworkUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for DeleteSubnetResponse
func (this *DeleteSubnetResponse) MarshalJSON() ([]byte, error) {
	str, err := NetworkMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for DeleteSubnetResponse
func (this *DeleteSubnetResponse) UnmarshalJSON(b []byte) error {
	return NetworkUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for DeleteIPPoolRequest
func (this *DeleteIPPoolRequest) MarshalJSON() ([]byte, error) {
	str, err := NetworkMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for DeleteIPPoolRequest
func (this *DeleteIPPoolRequest) UnmarshalJSON(b []byte) error {
	return NetworkUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for DeleteIPPoolResponse
func (this *DeleteIPPoolResponse) MarshalJSON() ([]byte, error) {
	str, err := NetworkMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for DeleteIPPoolResponse
func (this *DeleteIPPoolResponse) UnmarshalJSON(b []byte) error {
	return NetworkUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for ListMultusConfigsRequest
func (this *ListMultusConfigsRequest) MarshalJSON() ([]byte, error) {
	str, err := NetworkMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for ListMultusConfigsRequest
func (this *ListMultusConfigsRequest) UnmarshalJSON(b []byte) error {
	return NetworkUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for ListMultusConfigsResponse
func (this *ListMultusConfigsResponse) MarshalJSON() ([]byte, error) {
	str, err := NetworkMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for ListMultusConfigsResponse
func (this *ListMultusConfigsResponse) UnmarshalJSON(b []byte) error {
	return NetworkUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for ListSubnetsRequest
func (this *ListSubnetsRequest) MarshalJSON() ([]byte, error) {
	str, err := NetworkMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for ListSubnetsRequest
func (this *ListSubnetsRequest) UnmarshalJSON(b []byte) error {
	return NetworkUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for ListSubnetsResponse
func (this *ListSubnetsResponse) MarshalJSON() ([]byte, error) {
	str, err := NetworkMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for ListSubnetsResponse
func (this *ListSubnetsResponse) UnmarshalJSON(b []byte) error {
	return NetworkUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for ListIPPoolsRequest
func (this *ListIPPoolsRequest) MarshalJSON() ([]byte, error) {
	str, err := NetworkMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for ListIPPoolsRequest
func (this *ListIPPoolsRequest) UnmarshalJSON(b []byte) error {
	return NetworkUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for ListIPPoolsResponse
func (this *ListIPPoolsResponse) MarshalJSON() ([]byte, error) {
	str, err := NetworkMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for ListIPPoolsResponse
func (this *ListIPPoolsResponse) UnmarshalJSON(b []byte) error {
	return NetworkUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	NetworkMarshaler   = &jsonpb.Marshaler{}
	NetworkUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
