// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package v1alpha1

import (
	proto "github.com/golang/protobuf/proto"
)

// DeepCopyInto supports using Events within kubernetes types, where deepcopy-gen is used.
func (in *Events) DeepCopyInto(out *Events) {
	p := proto.Clone(in).(*Events)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Events. Required by controller-gen.
func (in *Events) DeepCopy() *Events {
	if in == nil {
		return nil
	}
	out := new(Events)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Events. Required by controller-gen.
func (in *Events) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ListEventsRequest within kubernetes types, where deepcopy-gen is used.
func (in *ListEventsRequest) DeepCopyInto(out *ListEventsRequest) {
	p := proto.Clone(in).(*ListEventsRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListEventsRequest. Required by controller-gen.
func (in *ListEventsRequest) DeepCopy() *ListEventsRequest {
	if in == nil {
		return nil
	}
	out := new(ListEventsRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ListEventsRequest. Required by controller-gen.
func (in *ListEventsRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
