// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "management/events/v1alpha1/events.proto" (package "vink.kubevm.io.apis.management.events.v1alpha1", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { EventsManagement } from "./events";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { Events } from "./events";
import type { ListEventsRequest } from "./events";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service vink.kubevm.io.apis.management.events.v1alpha1.EventsManagement
 */
export interface IEventsManagementClient {
    /**
     * @generated from protobuf rpc: List(vink.kubevm.io.apis.management.events.v1alpha1.ListEventsRequest) returns (vink.kubevm.io.apis.management.events.v1alpha1.Events);
     */
    list(input: ListEventsRequest, options?: RpcOptions): UnaryCall<ListEventsRequest, Events>;
}
/**
 * @generated from protobuf service vink.kubevm.io.apis.management.events.v1alpha1.EventsManagement
 */
export class EventsManagementClient implements IEventsManagementClient, ServiceInfo {
    typeName = EventsManagement.typeName;
    methods = EventsManagement.methods;
    options = EventsManagement.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: List(vink.kubevm.io.apis.management.events.v1alpha1.ListEventsRequest) returns (vink.kubevm.io.apis.management.events.v1alpha1.Events);
     */
    list(input: ListEventsRequest, options?: RpcOptions): UnaryCall<ListEventsRequest, Events> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListEventsRequest, Events>("unary", this._transport, method, opt, input);
    }
}
