// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package common

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for Resources
func (this *Resources) MarshalJSON() ([]byte, error) {
	str, err := K8SMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Resources
func (this *Resources) UnmarshalJSON(b []byte) error {
	return K8SUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for KubeEnv
func (this *KubeEnv) MarshalJSON() ([]byte, error) {
	str, err := K8SMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for KubeEnv
func (this *KubeEnv) UnmarshalJSON(b []byte) error {
	return K8SUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for KubeVolume
func (this *KubeVolume) MarshalJSON() ([]byte, error) {
	str, err := K8SMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for KubeVolume
func (this *KubeVolume) UnmarshalJSON(b []byte) error {
	return K8SUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for PodConfig
func (this *PodConfig) MarshalJSON() ([]byte, error) {
	str, err := K8SMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for PodConfig
func (this *PodConfig) UnmarshalJSON(b []byte) error {
	return K8SUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for Affinity
func (this *Affinity) MarshalJSON() ([]byte, error) {
	str, err := K8SMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Affinity
func (this *Affinity) UnmarshalJSON(b []byte) error {
	return K8SUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for PodAntiAffinity
func (this *PodAntiAffinity) MarshalJSON() ([]byte, error) {
	str, err := K8SMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for PodAntiAffinity
func (this *PodAntiAffinity) UnmarshalJSON(b []byte) error {
	return K8SUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for PodAffinityTerm
func (this *PodAffinityTerm) MarshalJSON() ([]byte, error) {
	str, err := K8SMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for PodAffinityTerm
func (this *PodAffinityTerm) UnmarshalJSON(b []byte) error {
	return K8SUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for LabelSelector
func (this *LabelSelector) MarshalJSON() ([]byte, error) {
	str, err := K8SMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for LabelSelector
func (this *LabelSelector) UnmarshalJSON(b []byte) error {
	return K8SUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for WeightedPodAffinityTerm
func (this *WeightedPodAffinityTerm) MarshalJSON() ([]byte, error) {
	str, err := K8SMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for WeightedPodAffinityTerm
func (this *WeightedPodAffinityTerm) UnmarshalJSON(b []byte) error {
	return K8SUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for PodAffinity
func (this *PodAffinity) MarshalJSON() ([]byte, error) {
	str, err := K8SMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for PodAffinity
func (this *PodAffinity) UnmarshalJSON(b []byte) error {
	return K8SUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for NodeAffinity
func (this *NodeAffinity) MarshalJSON() ([]byte, error) {
	str, err := K8SMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for NodeAffinity
func (this *NodeAffinity) UnmarshalJSON(b []byte) error {
	return K8SUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for NodeSelector
func (this *NodeSelector) MarshalJSON() ([]byte, error) {
	str, err := K8SMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for NodeSelector
func (this *NodeSelector) UnmarshalJSON(b []byte) error {
	return K8SUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for PreferredSchedulingTerm
func (this *PreferredSchedulingTerm) MarshalJSON() ([]byte, error) {
	str, err := K8SMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for PreferredSchedulingTerm
func (this *PreferredSchedulingTerm) UnmarshalJSON(b []byte) error {
	return K8SUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for NodeSelectorTerm
func (this *NodeSelectorTerm) MarshalJSON() ([]byte, error) {
	str, err := K8SMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for NodeSelectorTerm
func (this *NodeSelectorTerm) UnmarshalJSON(b []byte) error {
	return K8SUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for NodeSelectorRequirement
func (this *NodeSelectorRequirement) MarshalJSON() ([]byte, error) {
	str, err := K8SMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for NodeSelectorRequirement
func (this *NodeSelectorRequirement) UnmarshalJSON(b []byte) error {
	return K8SUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for LabelSelectorRequirement
func (this *LabelSelectorRequirement) MarshalJSON() ([]byte, error) {
	str, err := K8SMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for LabelSelectorRequirement
func (this *LabelSelectorRequirement) UnmarshalJSON(b []byte) error {
	return K8SUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	K8SMarshaler   = &jsonpb.Marshaler{}
	K8SUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
