// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package common

import (
	jsonpb "github.com/golang/protobuf/jsonpb"
)

var (
	OperatingSystemMarshaler   = &jsonpb.Marshaler{}
	OperatingSystemUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
