apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
  - https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/master/client/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
  - https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/master/client/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
  - https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/master/client/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml
  - https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/master/deploy/kubernetes/snapshot-controller/rbac-snapshot-controller.yaml
  - https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/master/deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
  - https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/master/deploy/kubernetes/csi-snapshotter/rbac-csi-snapshotter.yaml
  - https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/master/deploy/kubernetes/csi-snapshotter/rbac-external-provisioner.yaml
  - https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/master/deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml

patches:
  - target:
      kind: ClusterRoleBinding
      name: csi-snapshotter-role
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: kube-system
  - target:
      kind: Role
      name: external-snapshotter-leaderelection
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: kube-system
  - target:
      kind: RoleBinding
      name: external-snapshotter-leaderelection
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: kube-system
      - op: replace
        path: /subjects/0/namespace
        value: kube-system

  - target:
      kind: ServiceAccount
      name: csi-provisioner
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: kube-system
  - target:
      kind: ClusterRoleBinding
      name: csi-provisioner
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: kube-system
  - target:
      kind: Role
      name: external-provisioner-cfg
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: kube-system
  - target:
      kind: RoleBinding
      name: csi-provisioner-role-cfg
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: kube-system
      - op: replace
        path: /subjects/0/namespace
        value: kube-system

  - target:
      kind: ClusterRoleBinding
      name: csi-snapshotter
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: kube-system
  - target:
      kind: RoleBinding
      name: csi-snapshotter-provisioner-role-cfg
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: kube-system
      - op: replace
        path: /subjects/0/namespace
        value: kube-system
