// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: management/virtualmachine/v1alpha1/virtualmachine.proto

package v1alpha1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on VirtualMachine with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *VirtualMachine) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on VirtualMachine with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in VirtualMachineMultiError,
// or nil if none found.
func (m *VirtualMachine) ValidateAll() error {
	return m.validate(true)
}

func (m *VirtualMachine) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Namespace

	// no validation rules for Name

	if all {
		switch v := interface{}(m.GetVirtualMachine()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, VirtualMachineValidationError{
					field:  "VirtualMachine",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, VirtualMachineValidationError{
					field:  "VirtualMachine",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetVirtualMachine()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return VirtualMachineValidationError{
				field:  "VirtualMachine",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetVirtualMachineInstance()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, VirtualMachineValidationError{
					field:  "VirtualMachineInstance",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, VirtualMachineValidationError{
					field:  "VirtualMachineInstance",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetVirtualMachineInstance()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return VirtualMachineValidationError{
				field:  "VirtualMachineInstance",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetVirtualMachineDisk()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, VirtualMachineValidationError{
					field:  "VirtualMachineDisk",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, VirtualMachineValidationError{
					field:  "VirtualMachineDisk",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetVirtualMachineDisk()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return VirtualMachineValidationError{
				field:  "VirtualMachineDisk",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetCreationTimestamp()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, VirtualMachineValidationError{
					field:  "CreationTimestamp",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, VirtualMachineValidationError{
					field:  "CreationTimestamp",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreationTimestamp()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return VirtualMachineValidationError{
				field:  "CreationTimestamp",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return VirtualMachineMultiError(errors)
	}

	return nil
}

// VirtualMachineMultiError is an error wrapping multiple validation errors
// returned by VirtualMachine.ValidateAll() if the designated constraints
// aren't met.
type VirtualMachineMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m VirtualMachineMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m VirtualMachineMultiError) AllErrors() []error { return m }

// VirtualMachineValidationError is the validation error returned by
// VirtualMachine.Validate if the designated constraints aren't met.
type VirtualMachineValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VirtualMachineValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VirtualMachineValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VirtualMachineValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VirtualMachineValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VirtualMachineValidationError) ErrorName() string { return "VirtualMachineValidationError" }

// Error satisfies the builtin error interface
func (e VirtualMachineValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVirtualMachine.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VirtualMachineValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VirtualMachineValidationError{}

// Validate checks the field values on VirtualMachineInstance with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *VirtualMachineInstance) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on VirtualMachineInstance with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// VirtualMachineInstanceMultiError, or nil if none found.
func (m *VirtualMachineInstance) ValidateAll() error {
	return m.validate(true)
}

func (m *VirtualMachineInstance) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Namespace

	// no validation rules for Name

	if all {
		switch v := interface{}(m.GetSpec()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, VirtualMachineInstanceValidationError{
					field:  "Spec",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, VirtualMachineInstanceValidationError{
					field:  "Spec",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSpec()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return VirtualMachineInstanceValidationError{
				field:  "Spec",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetStatus()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, VirtualMachineInstanceValidationError{
					field:  "Status",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, VirtualMachineInstanceValidationError{
					field:  "Status",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStatus()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return VirtualMachineInstanceValidationError{
				field:  "Status",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return VirtualMachineInstanceMultiError(errors)
	}

	return nil
}

// VirtualMachineInstanceMultiError is an error wrapping multiple validation
// errors returned by VirtualMachineInstance.ValidateAll() if the designated
// constraints aren't met.
type VirtualMachineInstanceMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m VirtualMachineInstanceMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m VirtualMachineInstanceMultiError) AllErrors() []error { return m }

// VirtualMachineInstanceValidationError is the validation error returned by
// VirtualMachineInstance.Validate if the designated constraints aren't met.
type VirtualMachineInstanceValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VirtualMachineInstanceValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VirtualMachineInstanceValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VirtualMachineInstanceValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VirtualMachineInstanceValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VirtualMachineInstanceValidationError) ErrorName() string {
	return "VirtualMachineInstanceValidationError"
}

// Error satisfies the builtin error interface
func (e VirtualMachineInstanceValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVirtualMachineInstance.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VirtualMachineInstanceValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VirtualMachineInstanceValidationError{}

// Validate checks the field values on VirtualMachineConfig with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *VirtualMachineConfig) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on VirtualMachineConfig with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// VirtualMachineConfigMultiError, or nil if none found.
func (m *VirtualMachineConfig) ValidateAll() error {
	return m.validate(true)
}

func (m *VirtualMachineConfig) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetStorage()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, VirtualMachineConfigValidationError{
					field:  "Storage",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, VirtualMachineConfigValidationError{
					field:  "Storage",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStorage()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return VirtualMachineConfigValidationError{
				field:  "Storage",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetNetwork()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, VirtualMachineConfigValidationError{
					field:  "Network",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, VirtualMachineConfigValidationError{
					field:  "Network",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetNetwork()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return VirtualMachineConfigValidationError{
				field:  "Network",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetResources()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, VirtualMachineConfigValidationError{
					field:  "Resources",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, VirtualMachineConfigValidationError{
					field:  "Resources",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetResources()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return VirtualMachineConfigValidationError{
				field:  "Resources",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUserConfig()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, VirtualMachineConfigValidationError{
					field:  "UserConfig",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, VirtualMachineConfigValidationError{
					field:  "UserConfig",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUserConfig()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return VirtualMachineConfigValidationError{
				field:  "UserConfig",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return VirtualMachineConfigMultiError(errors)
	}

	return nil
}

// VirtualMachineConfigMultiError is an error wrapping multiple validation
// errors returned by VirtualMachineConfig.ValidateAll() if the designated
// constraints aren't met.
type VirtualMachineConfigMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m VirtualMachineConfigMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m VirtualMachineConfigMultiError) AllErrors() []error { return m }

// VirtualMachineConfigValidationError is the validation error returned by
// VirtualMachineConfig.Validate if the designated constraints aren't met.
type VirtualMachineConfigValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VirtualMachineConfigValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VirtualMachineConfigValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VirtualMachineConfigValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VirtualMachineConfigValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VirtualMachineConfigValidationError) ErrorName() string {
	return "VirtualMachineConfigValidationError"
}

// Error satisfies the builtin error interface
func (e VirtualMachineConfigValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVirtualMachineConfig.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VirtualMachineConfigValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VirtualMachineConfigValidationError{}

// Validate checks the field values on CreateVirtualMachineRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateVirtualMachineRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateVirtualMachineRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateVirtualMachineRequestMultiError, or nil if none found.
func (m *CreateVirtualMachineRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateVirtualMachineRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Namespace

	// no validation rules for Name

	if all {
		switch v := interface{}(m.GetConfig()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateVirtualMachineRequestValidationError{
					field:  "Config",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateVirtualMachineRequestValidationError{
					field:  "Config",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetConfig()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateVirtualMachineRequestValidationError{
				field:  "Config",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateVirtualMachineRequestMultiError(errors)
	}

	return nil
}

// CreateVirtualMachineRequestMultiError is an error wrapping multiple
// validation errors returned by CreateVirtualMachineRequest.ValidateAll() if
// the designated constraints aren't met.
type CreateVirtualMachineRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateVirtualMachineRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateVirtualMachineRequestMultiError) AllErrors() []error { return m }

// CreateVirtualMachineRequestValidationError is the validation error returned
// by CreateVirtualMachineRequest.Validate if the designated constraints
// aren't met.
type CreateVirtualMachineRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateVirtualMachineRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateVirtualMachineRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateVirtualMachineRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateVirtualMachineRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateVirtualMachineRequestValidationError) ErrorName() string {
	return "CreateVirtualMachineRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateVirtualMachineRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateVirtualMachineRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateVirtualMachineRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateVirtualMachineRequestValidationError{}

// Validate checks the field values on DeleteVirtualMachineRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteVirtualMachineRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteVirtualMachineRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteVirtualMachineRequestMultiError, or nil if none found.
func (m *DeleteVirtualMachineRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteVirtualMachineRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Namespace

	// no validation rules for Name

	if len(errors) > 0 {
		return DeleteVirtualMachineRequestMultiError(errors)
	}

	return nil
}

// DeleteVirtualMachineRequestMultiError is an error wrapping multiple
// validation errors returned by DeleteVirtualMachineRequest.ValidateAll() if
// the designated constraints aren't met.
type DeleteVirtualMachineRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteVirtualMachineRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteVirtualMachineRequestMultiError) AllErrors() []error { return m }

// DeleteVirtualMachineRequestValidationError is the validation error returned
// by DeleteVirtualMachineRequest.Validate if the designated constraints
// aren't met.
type DeleteVirtualMachineRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteVirtualMachineRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteVirtualMachineRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteVirtualMachineRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteVirtualMachineRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteVirtualMachineRequestValidationError) ErrorName() string {
	return "DeleteVirtualMachineRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteVirtualMachineRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteVirtualMachineRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteVirtualMachineRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteVirtualMachineRequestValidationError{}

// Validate checks the field values on DeleteVirtualMachineResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteVirtualMachineResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteVirtualMachineResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteVirtualMachineResponseMultiError, or nil if none found.
func (m *DeleteVirtualMachineResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteVirtualMachineResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DeleteVirtualMachineResponseMultiError(errors)
	}

	return nil
}

// DeleteVirtualMachineResponseMultiError is an error wrapping multiple
// validation errors returned by DeleteVirtualMachineResponse.ValidateAll() if
// the designated constraints aren't met.
type DeleteVirtualMachineResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteVirtualMachineResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteVirtualMachineResponseMultiError) AllErrors() []error { return m }

// DeleteVirtualMachineResponseValidationError is the validation error returned
// by DeleteVirtualMachineResponse.Validate if the designated constraints
// aren't met.
type DeleteVirtualMachineResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteVirtualMachineResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteVirtualMachineResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteVirtualMachineResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteVirtualMachineResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteVirtualMachineResponseValidationError) ErrorName() string {
	return "DeleteVirtualMachineResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteVirtualMachineResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteVirtualMachineResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteVirtualMachineResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteVirtualMachineResponseValidationError{}

// Validate checks the field values on ListVirtualMachinesRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListVirtualMachinesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListVirtualMachinesRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListVirtualMachinesRequestMultiError, or nil if none found.
func (m *ListVirtualMachinesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListVirtualMachinesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Namespace

	if all {
		switch v := interface{}(m.GetOptions()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListVirtualMachinesRequestValidationError{
					field:  "Options",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListVirtualMachinesRequestValidationError{
					field:  "Options",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetOptions()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListVirtualMachinesRequestValidationError{
				field:  "Options",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ListVirtualMachinesRequestMultiError(errors)
	}

	return nil
}

// ListVirtualMachinesRequestMultiError is an error wrapping multiple
// validation errors returned by ListVirtualMachinesRequest.ValidateAll() if
// the designated constraints aren't met.
type ListVirtualMachinesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListVirtualMachinesRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListVirtualMachinesRequestMultiError) AllErrors() []error { return m }

// ListVirtualMachinesRequestValidationError is the validation error returned
// by ListVirtualMachinesRequest.Validate if the designated constraints aren't met.
type ListVirtualMachinesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListVirtualMachinesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListVirtualMachinesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListVirtualMachinesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListVirtualMachinesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListVirtualMachinesRequestValidationError) ErrorName() string {
	return "ListVirtualMachinesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListVirtualMachinesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListVirtualMachinesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListVirtualMachinesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListVirtualMachinesRequestValidationError{}

// Validate checks the field values on ListVirtualMachinesResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListVirtualMachinesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListVirtualMachinesResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListVirtualMachinesResponseMultiError, or nil if none found.
func (m *ListVirtualMachinesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListVirtualMachinesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListVirtualMachinesResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListVirtualMachinesResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListVirtualMachinesResponseValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if all {
		switch v := interface{}(m.GetOptions()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListVirtualMachinesResponseValidationError{
					field:  "Options",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListVirtualMachinesResponseValidationError{
					field:  "Options",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetOptions()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListVirtualMachinesResponseValidationError{
				field:  "Options",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ListVirtualMachinesResponseMultiError(errors)
	}

	return nil
}

// ListVirtualMachinesResponseMultiError is an error wrapping multiple
// validation errors returned by ListVirtualMachinesResponse.ValidateAll() if
// the designated constraints aren't met.
type ListVirtualMachinesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListVirtualMachinesResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListVirtualMachinesResponseMultiError) AllErrors() []error { return m }

// ListVirtualMachinesResponseValidationError is the validation error returned
// by ListVirtualMachinesResponse.Validate if the designated constraints
// aren't met.
type ListVirtualMachinesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListVirtualMachinesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListVirtualMachinesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListVirtualMachinesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListVirtualMachinesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListVirtualMachinesResponseValidationError) ErrorName() string {
	return "ListVirtualMachinesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListVirtualMachinesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListVirtualMachinesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListVirtualMachinesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListVirtualMachinesResponseValidationError{}

// Validate checks the field values on ManageVirtualMachinePowerStateRequest
// with the rules defined in the proto definition for this message. If any
// rules are violated, the first error encountered is returned, or nil if
// there are no violations.
func (m *ManageVirtualMachinePowerStateRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ManageVirtualMachinePowerStateRequest
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// ManageVirtualMachinePowerStateRequestMultiError, or nil if none found.
func (m *ManageVirtualMachinePowerStateRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ManageVirtualMachinePowerStateRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Namespace

	// no validation rules for Name

	// no validation rules for PowerState

	if len(errors) > 0 {
		return ManageVirtualMachinePowerStateRequestMultiError(errors)
	}

	return nil
}

// ManageVirtualMachinePowerStateRequestMultiError is an error wrapping
// multiple validation errors returned by
// ManageVirtualMachinePowerStateRequest.ValidateAll() if the designated
// constraints aren't met.
type ManageVirtualMachinePowerStateRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ManageVirtualMachinePowerStateRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ManageVirtualMachinePowerStateRequestMultiError) AllErrors() []error { return m }

// ManageVirtualMachinePowerStateRequestValidationError is the validation error
// returned by ManageVirtualMachinePowerStateRequest.Validate if the
// designated constraints aren't met.
type ManageVirtualMachinePowerStateRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ManageVirtualMachinePowerStateRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ManageVirtualMachinePowerStateRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ManageVirtualMachinePowerStateRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ManageVirtualMachinePowerStateRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ManageVirtualMachinePowerStateRequestValidationError) ErrorName() string {
	return "ManageVirtualMachinePowerStateRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ManageVirtualMachinePowerStateRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sManageVirtualMachinePowerStateRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ManageVirtualMachinePowerStateRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ManageVirtualMachinePowerStateRequestValidationError{}

// Validate checks the field values on VirtualMachine_Disk with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *VirtualMachine_Disk) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on VirtualMachine_Disk with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// VirtualMachine_DiskMultiError, or nil if none found.
func (m *VirtualMachine_Disk) ValidateAll() error {
	return m.validate(true)
}

func (m *VirtualMachine_Disk) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetRoot()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, VirtualMachine_DiskValidationError{
					field:  "Root",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, VirtualMachine_DiskValidationError{
					field:  "Root",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRoot()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return VirtualMachine_DiskValidationError{
				field:  "Root",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetData() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, VirtualMachine_DiskValidationError{
						field:  fmt.Sprintf("Data[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, VirtualMachine_DiskValidationError{
						field:  fmt.Sprintf("Data[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return VirtualMachine_DiskValidationError{
					field:  fmt.Sprintf("Data[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return VirtualMachine_DiskMultiError(errors)
	}

	return nil
}

// VirtualMachine_DiskMultiError is an error wrapping multiple validation
// errors returned by VirtualMachine_Disk.ValidateAll() if the designated
// constraints aren't met.
type VirtualMachine_DiskMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m VirtualMachine_DiskMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m VirtualMachine_DiskMultiError) AllErrors() []error { return m }

// VirtualMachine_DiskValidationError is the validation error returned by
// VirtualMachine_Disk.Validate if the designated constraints aren't met.
type VirtualMachine_DiskValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VirtualMachine_DiskValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VirtualMachine_DiskValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VirtualMachine_DiskValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VirtualMachine_DiskValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VirtualMachine_DiskValidationError) ErrorName() string {
	return "VirtualMachine_DiskValidationError"
}

// Error satisfies the builtin error interface
func (e VirtualMachine_DiskValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVirtualMachine_Disk.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VirtualMachine_DiskValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VirtualMachine_DiskValidationError{}

// Validate checks the field values on VirtualMachineConfig_NamespaceNamed with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *VirtualMachineConfig_NamespaceNamed) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on VirtualMachineConfig_NamespaceNamed
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// VirtualMachineConfig_NamespaceNamedMultiError, or nil if none found.
func (m *VirtualMachineConfig_NamespaceNamed) ValidateAll() error {
	return m.validate(true)
}

func (m *VirtualMachineConfig_NamespaceNamed) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Namespace

	// no validation rules for Name

	if len(errors) > 0 {
		return VirtualMachineConfig_NamespaceNamedMultiError(errors)
	}

	return nil
}

// VirtualMachineConfig_NamespaceNamedMultiError is an error wrapping multiple
// validation errors returned by
// VirtualMachineConfig_NamespaceNamed.ValidateAll() if the designated
// constraints aren't met.
type VirtualMachineConfig_NamespaceNamedMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m VirtualMachineConfig_NamespaceNamedMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m VirtualMachineConfig_NamespaceNamedMultiError) AllErrors() []error { return m }

// VirtualMachineConfig_NamespaceNamedValidationError is the validation error
// returned by VirtualMachineConfig_NamespaceNamed.Validate if the designated
// constraints aren't met.
type VirtualMachineConfig_NamespaceNamedValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VirtualMachineConfig_NamespaceNamedValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VirtualMachineConfig_NamespaceNamedValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VirtualMachineConfig_NamespaceNamedValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VirtualMachineConfig_NamespaceNamedValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VirtualMachineConfig_NamespaceNamedValidationError) ErrorName() string {
	return "VirtualMachineConfig_NamespaceNamedValidationError"
}

// Error satisfies the builtin error interface
func (e VirtualMachineConfig_NamespaceNamedValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVirtualMachineConfig_NamespaceNamed.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VirtualMachineConfig_NamespaceNamedValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VirtualMachineConfig_NamespaceNamedValidationError{}

// Validate checks the field values on VirtualMachineConfig_Storage with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *VirtualMachineConfig_Storage) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on VirtualMachineConfig_Storage with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// VirtualMachineConfig_StorageMultiError, or nil if none found.
func (m *VirtualMachineConfig_Storage) ValidateAll() error {
	return m.validate(true)
}

func (m *VirtualMachineConfig_Storage) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetBootDisk()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, VirtualMachineConfig_StorageValidationError{
					field:  "BootDisk",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, VirtualMachineConfig_StorageValidationError{
					field:  "BootDisk",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetBootDisk()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return VirtualMachineConfig_StorageValidationError{
				field:  "BootDisk",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetDataDisks() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, VirtualMachineConfig_StorageValidationError{
						field:  fmt.Sprintf("DataDisks[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, VirtualMachineConfig_StorageValidationError{
						field:  fmt.Sprintf("DataDisks[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return VirtualMachineConfig_StorageValidationError{
					field:  fmt.Sprintf("DataDisks[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return VirtualMachineConfig_StorageMultiError(errors)
	}

	return nil
}

// VirtualMachineConfig_StorageMultiError is an error wrapping multiple
// validation errors returned by VirtualMachineConfig_Storage.ValidateAll() if
// the designated constraints aren't met.
type VirtualMachineConfig_StorageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m VirtualMachineConfig_StorageMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m VirtualMachineConfig_StorageMultiError) AllErrors() []error { return m }

// VirtualMachineConfig_StorageValidationError is the validation error returned
// by VirtualMachineConfig_Storage.Validate if the designated constraints
// aren't met.
type VirtualMachineConfig_StorageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VirtualMachineConfig_StorageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VirtualMachineConfig_StorageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VirtualMachineConfig_StorageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VirtualMachineConfig_StorageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VirtualMachineConfig_StorageValidationError) ErrorName() string {
	return "VirtualMachineConfig_StorageValidationError"
}

// Error satisfies the builtin error interface
func (e VirtualMachineConfig_StorageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVirtualMachineConfig_Storage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VirtualMachineConfig_StorageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VirtualMachineConfig_StorageValidationError{}

// Validate checks the field values on VirtualMachineConfig_Network with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *VirtualMachineConfig_Network) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on VirtualMachineConfig_Network with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// VirtualMachineConfig_NetworkMultiError, or nil if none found.
func (m *VirtualMachineConfig_Network) ValidateAll() error {
	return m.validate(true)
}

func (m *VirtualMachineConfig_Network) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for MultusConfigRef

	// no validation rules for IppoolRef

	if len(errors) > 0 {
		return VirtualMachineConfig_NetworkMultiError(errors)
	}

	return nil
}

// VirtualMachineConfig_NetworkMultiError is an error wrapping multiple
// validation errors returned by VirtualMachineConfig_Network.ValidateAll() if
// the designated constraints aren't met.
type VirtualMachineConfig_NetworkMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m VirtualMachineConfig_NetworkMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m VirtualMachineConfig_NetworkMultiError) AllErrors() []error { return m }

// VirtualMachineConfig_NetworkValidationError is the validation error returned
// by VirtualMachineConfig_Network.Validate if the designated constraints
// aren't met.
type VirtualMachineConfig_NetworkValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VirtualMachineConfig_NetworkValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VirtualMachineConfig_NetworkValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VirtualMachineConfig_NetworkValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VirtualMachineConfig_NetworkValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VirtualMachineConfig_NetworkValidationError) ErrorName() string {
	return "VirtualMachineConfig_NetworkValidationError"
}

// Error satisfies the builtin error interface
func (e VirtualMachineConfig_NetworkValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVirtualMachineConfig_Network.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VirtualMachineConfig_NetworkValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VirtualMachineConfig_NetworkValidationError{}

// Validate checks the field values on VirtualMachineConfig_Resources with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *VirtualMachineConfig_Resources) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on VirtualMachineConfig_Resources with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// VirtualMachineConfig_ResourcesMultiError, or nil if none found.
func (m *VirtualMachineConfig_Resources) ValidateAll() error {
	return m.validate(true)
}

func (m *VirtualMachineConfig_Resources) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for CpuCores

	// no validation rules for Memory

	if len(errors) > 0 {
		return VirtualMachineConfig_ResourcesMultiError(errors)
	}

	return nil
}

// VirtualMachineConfig_ResourcesMultiError is an error wrapping multiple
// validation errors returned by VirtualMachineConfig_Resources.ValidateAll()
// if the designated constraints aren't met.
type VirtualMachineConfig_ResourcesMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m VirtualMachineConfig_ResourcesMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m VirtualMachineConfig_ResourcesMultiError) AllErrors() []error { return m }

// VirtualMachineConfig_ResourcesValidationError is the validation error
// returned by VirtualMachineConfig_Resources.Validate if the designated
// constraints aren't met.
type VirtualMachineConfig_ResourcesValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VirtualMachineConfig_ResourcesValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VirtualMachineConfig_ResourcesValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VirtualMachineConfig_ResourcesValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VirtualMachineConfig_ResourcesValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VirtualMachineConfig_ResourcesValidationError) ErrorName() string {
	return "VirtualMachineConfig_ResourcesValidationError"
}

// Error satisfies the builtin error interface
func (e VirtualMachineConfig_ResourcesValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVirtualMachineConfig_Resources.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VirtualMachineConfig_ResourcesValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VirtualMachineConfig_ResourcesValidationError{}

// Validate checks the field values on VirtualMachineConfig_UserConfig with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *VirtualMachineConfig_UserConfig) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on VirtualMachineConfig_UserConfig with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// VirtualMachineConfig_UserConfigMultiError, or nil if none found.
func (m *VirtualMachineConfig_UserConfig) ValidateAll() error {
	return m.validate(true)
}

func (m *VirtualMachineConfig_UserConfig) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for CloudInitBase64

	if len(errors) > 0 {
		return VirtualMachineConfig_UserConfigMultiError(errors)
	}

	return nil
}

// VirtualMachineConfig_UserConfigMultiError is an error wrapping multiple
// validation errors returned by VirtualMachineConfig_UserConfig.ValidateAll()
// if the designated constraints aren't met.
type VirtualMachineConfig_UserConfigMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m VirtualMachineConfig_UserConfigMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m VirtualMachineConfig_UserConfigMultiError) AllErrors() []error { return m }

// VirtualMachineConfig_UserConfigValidationError is the validation error
// returned by VirtualMachineConfig_UserConfig.Validate if the designated
// constraints aren't met.
type VirtualMachineConfig_UserConfigValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VirtualMachineConfig_UserConfigValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VirtualMachineConfig_UserConfigValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VirtualMachineConfig_UserConfigValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VirtualMachineConfig_UserConfigValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VirtualMachineConfig_UserConfigValidationError) ErrorName() string {
	return "VirtualMachineConfig_UserConfigValidationError"
}

// Error satisfies the builtin error interface
func (e VirtualMachineConfig_UserConfigValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVirtualMachineConfig_UserConfig.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VirtualMachineConfig_UserConfigValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VirtualMachineConfig_UserConfigValidationError{}

// Validate checks the field values on VirtualMachineConfig_Storage_BootDisk
// with the rules defined in the proto definition for this message. If any
// rules are violated, the first error encountered is returned, or nil if
// there are no violations.
func (m *VirtualMachineConfig_Storage_BootDisk) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on VirtualMachineConfig_Storage_BootDisk
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// VirtualMachineConfig_Storage_BootDiskMultiError, or nil if none found.
func (m *VirtualMachineConfig_Storage_BootDisk) ValidateAll() error {
	return m.validate(true)
}

func (m *VirtualMachineConfig_Storage_BootDisk) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetDataVolumeRef()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, VirtualMachineConfig_Storage_BootDiskValidationError{
					field:  "DataVolumeRef",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, VirtualMachineConfig_Storage_BootDiskValidationError{
					field:  "DataVolumeRef",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDataVolumeRef()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return VirtualMachineConfig_Storage_BootDiskValidationError{
				field:  "DataVolumeRef",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Capacity

	// no validation rules for StorageClassName

	if len(errors) > 0 {
		return VirtualMachineConfig_Storage_BootDiskMultiError(errors)
	}

	return nil
}

// VirtualMachineConfig_Storage_BootDiskMultiError is an error wrapping
// multiple validation errors returned by
// VirtualMachineConfig_Storage_BootDisk.ValidateAll() if the designated
// constraints aren't met.
type VirtualMachineConfig_Storage_BootDiskMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m VirtualMachineConfig_Storage_BootDiskMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m VirtualMachineConfig_Storage_BootDiskMultiError) AllErrors() []error { return m }

// VirtualMachineConfig_Storage_BootDiskValidationError is the validation error
// returned by VirtualMachineConfig_Storage_BootDisk.Validate if the
// designated constraints aren't met.
type VirtualMachineConfig_Storage_BootDiskValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VirtualMachineConfig_Storage_BootDiskValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VirtualMachineConfig_Storage_BootDiskValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VirtualMachineConfig_Storage_BootDiskValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VirtualMachineConfig_Storage_BootDiskValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VirtualMachineConfig_Storage_BootDiskValidationError) ErrorName() string {
	return "VirtualMachineConfig_Storage_BootDiskValidationError"
}

// Error satisfies the builtin error interface
func (e VirtualMachineConfig_Storage_BootDiskValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVirtualMachineConfig_Storage_BootDisk.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VirtualMachineConfig_Storage_BootDiskValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VirtualMachineConfig_Storage_BootDiskValidationError{}

// Validate checks the field values on VirtualMachineConfig_Storage_DataDisk
// with the rules defined in the proto definition for this message. If any
// rules are violated, the first error encountered is returned, or nil if
// there are no violations.
func (m *VirtualMachineConfig_Storage_DataDisk) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on VirtualMachineConfig_Storage_DataDisk
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// VirtualMachineConfig_Storage_DataDiskMultiError, or nil if none found.
func (m *VirtualMachineConfig_Storage_DataDisk) ValidateAll() error {
	return m.validate(true)
}

func (m *VirtualMachineConfig_Storage_DataDisk) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for DataVolumeRef

	if len(errors) > 0 {
		return VirtualMachineConfig_Storage_DataDiskMultiError(errors)
	}

	return nil
}

// VirtualMachineConfig_Storage_DataDiskMultiError is an error wrapping
// multiple validation errors returned by
// VirtualMachineConfig_Storage_DataDisk.ValidateAll() if the designated
// constraints aren't met.
type VirtualMachineConfig_Storage_DataDiskMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m VirtualMachineConfig_Storage_DataDiskMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m VirtualMachineConfig_Storage_DataDiskMultiError) AllErrors() []error { return m }

// VirtualMachineConfig_Storage_DataDiskValidationError is the validation error
// returned by VirtualMachineConfig_Storage_DataDisk.Validate if the
// designated constraints aren't met.
type VirtualMachineConfig_Storage_DataDiskValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VirtualMachineConfig_Storage_DataDiskValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VirtualMachineConfig_Storage_DataDiskValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VirtualMachineConfig_Storage_DataDiskValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VirtualMachineConfig_Storage_DataDiskValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VirtualMachineConfig_Storage_DataDiskValidationError) ErrorName() string {
	return "VirtualMachineConfig_Storage_DataDiskValidationError"
}

// Error satisfies the builtin error interface
func (e VirtualMachineConfig_Storage_DataDiskValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVirtualMachineConfig_Storage_DataDisk.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VirtualMachineConfig_Storage_DataDiskValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VirtualMachineConfig_Storage_DataDiskValidationError{}
