// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package v1alpha1

import (
	proto "github.com/golang/protobuf/proto"
)

// DeepCopyInto supports using NamespaceConfig within kubernetes types, where deepcopy-gen is used.
func (in *NamespaceConfig) DeepCopyInto(out *NamespaceConfig) {
	p := proto.Clone(in).(*NamespaceConfig)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceConfig. Required by controller-gen.
func (in *NamespaceConfig) DeepCopy() *NamespaceConfig {
	if in == nil {
		return nil
	}
	out := new(NamespaceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceConfig. Required by controller-gen.
func (in *NamespaceConfig) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Namespace within kubernetes types, where deepcopy-gen is used.
func (in *Namespace) DeepCopyInto(out *Namespace) {
	p := proto.Clone(in).(*Namespace)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Namespace. Required by controller-gen.
func (in *Namespace) DeepCopy() *Namespace {
	if in == nil {
		return nil
	}
	out := new(Namespace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Namespace. Required by controller-gen.
func (in *Namespace) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using CreateNamespaceRequest within kubernetes types, where deepcopy-gen is used.
func (in *CreateNamespaceRequest) DeepCopyInto(out *CreateNamespaceRequest) {
	p := proto.Clone(in).(*CreateNamespaceRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CreateNamespaceRequest. Required by controller-gen.
func (in *CreateNamespaceRequest) DeepCopy() *CreateNamespaceRequest {
	if in == nil {
		return nil
	}
	out := new(CreateNamespaceRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new CreateNamespaceRequest. Required by controller-gen.
func (in *CreateNamespaceRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using DeleteNamespaceRequest within kubernetes types, where deepcopy-gen is used.
func (in *DeleteNamespaceRequest) DeepCopyInto(out *DeleteNamespaceRequest) {
	p := proto.Clone(in).(*DeleteNamespaceRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteNamespaceRequest. Required by controller-gen.
func (in *DeleteNamespaceRequest) DeepCopy() *DeleteNamespaceRequest {
	if in == nil {
		return nil
	}
	out := new(DeleteNamespaceRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new DeleteNamespaceRequest. Required by controller-gen.
func (in *DeleteNamespaceRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using DeleteNamespaceResponse within kubernetes types, where deepcopy-gen is used.
func (in *DeleteNamespaceResponse) DeepCopyInto(out *DeleteNamespaceResponse) {
	p := proto.Clone(in).(*DeleteNamespaceResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteNamespaceResponse. Required by controller-gen.
func (in *DeleteNamespaceResponse) DeepCopy() *DeleteNamespaceResponse {
	if in == nil {
		return nil
	}
	out := new(DeleteNamespaceResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new DeleteNamespaceResponse. Required by controller-gen.
func (in *DeleteNamespaceResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ListNamespacesRequest within kubernetes types, where deepcopy-gen is used.
func (in *ListNamespacesRequest) DeepCopyInto(out *ListNamespacesRequest) {
	p := proto.Clone(in).(*ListNamespacesRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListNamespacesRequest. Required by controller-gen.
func (in *ListNamespacesRequest) DeepCopy() *ListNamespacesRequest {
	if in == nil {
		return nil
	}
	out := new(ListNamespacesRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ListNamespacesRequest. Required by controller-gen.
func (in *ListNamespacesRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ListNamespacesResponse within kubernetes types, where deepcopy-gen is used.
func (in *ListNamespacesResponse) DeepCopyInto(out *ListNamespacesResponse) {
	p := proto.Clone(in).(*ListNamespacesResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListNamespacesResponse. Required by controller-gen.
func (in *ListNamespacesResponse) DeepCopy() *ListNamespacesResponse {
	if in == nil {
		return nil
	}
	out := new(ListNamespacesResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ListNamespacesResponse. Required by controller-gen.
func (in *ListNamespacesResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
