apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "kubevirt.crUninstallHook.name" . }}
  {{ template "kubevirt.crUninstallHook.annotations" (dict "hookWeight" 1) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "kubevirt.crUninstallHook.name" . }}
  {{ template "kubevirt.crUninstallHook.annotations" (dict "hookWeight" 1) }}
rules:
  - apiGroups: [ "kubevirt.io" ]
    resources: [ "kubevirts" ]
    verbs: [ "*" ]
  - apiGroups: [ "apps" ]
    resources: [ "deployments", "daemonsets" ]
    verbs: [ "*" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "kubevirt.crUninstallHook.name" . }}
  {{ template "kubevirt.crUninstallHook.annotations" (dict "hookWeight" 2) }}
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ template "kubevirt.crUninstallHook.name" . }}
roleRef:
  kind: Role
  name: {{ template "kubevirt.crUninstallHook.name" . }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "kubevirt.crUninstallHook.name" . }}
  {{ template "kubevirt.crUninstallHook.annotations" (dict "hookWeight" 3) }}
spec:
  template:
    metadata:
      name: {{ template "kubevirt.crUninstallHook.name" . }}
    spec:
      serviceAccountName: {{ template "kubevirt.crUninstallHook.name" . }}
      restartPolicy: {{ .Values.hookRestartPolicy }}
      containers:
        - name: {{ template "kubevirt.crUninstallHook.name" . }}
          image: {{ .Values.hookImage }}
          securityContext:
            {{- toYaml .Values.hookSecurityContext | nindent 12 }}
          command: [ "/bin/bash", "-c" ]
          args:
            - >
              echo '[INFO] Deleting all kubevirt resources...';
              kubectl delete kubevirt --wait --all --ignore-not-found;

              echo '[INFO] Waiting for kubevirt to be fully deleted...';
              kubectl wait --for=delete kubevirts.kubevirt.io/kubevirt;

              echo '[INFO] Waiting for the virt-api deployment to be deleted...';
              kubectl wait --for=delete deployments/virt-api;

              echo '[INFO] Waiting for the virt-controller deployment to be deleted...';
              kubectl wait --for=delete deployments/virt-controller;

              echo '[INFO] Waiting for the virt-handler daemonset to be deleted...';
              kubectl wait --for=delete daemonsets/virt-handler;

              echo '[INFO] All kubevirt resources and deployments deletion steps completed.';

