apiVersion: v1
kind: Service
metadata:
  labels:
    app: vink-ui
    service: vink-ui
  name: vink-ui
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: vink-ui
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
