// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: types/node.proto

package types

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on NodeResourceMetrics with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *NodeResourceMetrics) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on NodeResourceMetrics with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// NodeResourceMetricsMultiError, or nil if none found.
func (m *NodeResourceMetrics) ValidateAll() error {
	return m.validate(true)
}

func (m *NodeResourceMetrics) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for CpuUsage

	// no validation rules for CpuTotal

	// no validation rules for MemeryUsage

	// no validation rules for MemeryTotal

	// no validation rules for StorageUsage

	// no validation rules for StorageTotal

	if len(errors) > 0 {
		return NodeResourceMetricsMultiError(errors)
	}

	return nil
}

// NodeResourceMetricsMultiError is an error wrapping multiple validation
// errors returned by NodeResourceMetrics.ValidateAll() if the designated
// constraints aren't met.
type NodeResourceMetricsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m NodeResourceMetricsMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m NodeResourceMetricsMultiError) AllErrors() []error { return m }

// NodeResourceMetricsValidationError is the validation error returned by
// NodeResourceMetrics.Validate if the designated constraints aren't met.
type NodeResourceMetricsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e NodeResourceMetricsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e NodeResourceMetricsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e NodeResourceMetricsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e NodeResourceMetricsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e NodeResourceMetricsValidationError) ErrorName() string {
	return "NodeResourceMetricsValidationError"
}

// Error satisfies the builtin error interface
func (e NodeResourceMetricsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNodeResourceMetrics.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = NodeResourceMetricsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = NodeResourceMetricsValidationError{}

// Validate checks the field values on NodeCephStorage with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *NodeCephStorage) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on NodeCephStorage with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// NodeCephStorageMultiError, or nil if none found.
func (m *NodeCephStorage) ValidateAll() error {
	return m.validate(true)
}

func (m *NodeCephStorage) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Osd

	// no validation rules for Up

	// no validation rules for BluestoreBdevDevNode

	// no validation rules for BluestoreBdevType

	// no validation rules for StorageUsage

	// no validation rules for StorageTotal

	if len(errors) > 0 {
		return NodeCephStorageMultiError(errors)
	}

	return nil
}

// NodeCephStorageMultiError is an error wrapping multiple validation errors
// returned by NodeCephStorage.ValidateAll() if the designated constraints
// aren't met.
type NodeCephStorageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m NodeCephStorageMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m NodeCephStorageMultiError) AllErrors() []error { return m }

// NodeCephStorageValidationError is the validation error returned by
// NodeCephStorage.Validate if the designated constraints aren't met.
type NodeCephStorageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e NodeCephStorageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e NodeCephStorageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e NodeCephStorageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e NodeCephStorageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e NodeCephStorageValidationError) ErrorName() string { return "NodeCephStorageValidationError" }

// Error satisfies the builtin error interface
func (e NodeCephStorageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNodeCephStorage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = NodeCephStorageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = NodeCephStorageValidationError{}
