// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package types

import (
	jsonpb "github.com/golang/protobuf/jsonpb"
)

var (
	ResourceTypeMarshaler   = &jsonpb.Marshaler{}
	ResourceTypeUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
