// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package types

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for VirtualMachineHost
func (this *VirtualMachineHost) MarshalJSON() ([]byte, error) {
	str, err := VirtualmachineMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for VirtualMachineHost
func (this *VirtualMachineHost) UnmarshalJSON(b []byte) error {
	return VirtualmachineUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for VirtualMachineResourceMetrics
func (this *VirtualMachineResourceMetrics) MarshalJSON() ([]byte, error) {
	str, err := VirtualmachineMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for VirtualMachineResourceMetrics
func (this *VirtualMachineResourceMetrics) UnmarshalJSON(b []byte) error {
	return VirtualmachineUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for VirtualMachineNetwork
func (this *VirtualMachineNetwork) MarshalJSON() ([]byte, error) {
	str, err := VirtualmachineMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for VirtualMachineNetwork
func (this *VirtualMachineNetwork) UnmarshalJSON(b []byte) error {
	return VirtualmachineUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for VirtualMachineDisk
func (this *VirtualMachineDisk) MarshalJSON() ([]byte, error) {
	str, err := VirtualmachineMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for VirtualMachineDisk
func (this *VirtualMachineDisk) UnmarshalJSON(b []byte) error {
	return VirtualmachineUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	VirtualmachineMarshaler   = &jsonpb.Marshaler{}
	VirtualmachineUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
