apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vink
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    # "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-20"
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - "*"
  - nonResourceURLs:
      - '*'
    verbs:
      - "*"
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vink
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    # "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-20"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vink
subjects:
  - kind: ServiceAccount
    name: vink
    namespace: {{ .Release.Namespace }}
