// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package v1alpha1

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for WatchRequest
func (this *WatchRequest) MarshalJSON() ([]byte, error) {
	str, err := WatchMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for WatchRequest
func (this *WatchRequest) UnmarshalJSON(b []byte) error {
	return WatchUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for WatchResponse
func (this *WatchResponse) MarshalJSON() ([]byte, error) {
	str, err := WatchMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for WatchResponse
func (this *WatchResponse) UnmarshalJSON(b []byte) error {
	return WatchUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for WatchOptions
func (this *WatchOptions) MarshalJSON() ([]byte, error) {
	str, err := WatchMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for WatchOptions
func (this *WatchOptions) UnmarshalJSON(b []byte) error {
	return WatchUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	WatchMarshaler   = &jsonpb.Marshaler{}
	WatchUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
