apiVersion: batch/v1
kind: Job
metadata:
  namespace: vink
  name: multus-installer
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "1"
spec:
  template:
    metadata:
      name: vink
    spec:
      serviceAccountName: vink
      restartPolicy: OnFailure
      containers:
        - name: multus-installer
          image: hejianmin/shell:0.0.1-4e596d93
          env:
          - name: HTTP_PROXY
            value: http://192.168.18.240:7897
          - name: HTTPS_PROXY
            value: http://192.168.18.240:7897
          - name: NO_PROXY
            value: localhost,127.0.0.1,10.233.0.1
          command:
            - kubectl
          args:
            - apply
            - -f
            - https://raw.githubusercontent.com/k8snetworkplumbingwg/multus-cni/master/deployments/multus-daemonset.yml
            - -n
            - kube-system
